module PushNotification

	require 'fcm'
	def send_notidication(device_keys)
		fcm = FCM.new(ENV.fcm_key) # Find server_key on: your firebase console on web > tab general > web api key
		registration_ids= [device_keys] # Array of keys generated by firebase for devices 
		options = {
		        priority: "high",
		        collapse_key: "updated_score", 
		        notification: {
		            title: "Message Title", 
		            body: "Hi, Worked perfectly",
		            icon: "myicon"}
		        }
		response = fcm.send(registration_ids, options)
	end

end