module PushNotification

	require 'fcm'
	def send_notidication(device_keys)
		fcm = FCM.new('AAAARoAcxik:APA91bH3YhwdcexjqMHKtfGIuwhC1huDz_mOYMbPpTLKwQsA28pxyVxS0N-S-WvmJbXBJL9HjBtTqF6YnXqgLxgy-9bBqjoV9DISd-g86LMDd27LIfHbyrEVo0ziO3M3Jok6diUwr9bc') # Find server_key on: your firebase console on web > tab general > web api key
		registration_ids= [device_keys] # Array of keys generated by firebase for devices
		options = {
		        priority: "high",
		        collapse_key: "updated_score",
		        notification: {
		            title: "Message Title",
		            body: "Hi, Worked perfectly",
		            icon: "myicon"}
		        }
		response = fcm.send(registration_ids, options)
	end

end
