production:
  fcm_key: 'AAAARoAcxik:APA91bH3YhwdcexjqMHKtfGIuwhC1huDz_mOYMbPpTLKwQsA28pxyVxS0N-S-WvmJbXBJL9HjBtTqF6YnXqgLxgy-9bBqjoV9DISd-g86LMDd27LIfHbyrEVo0ziO3M3Jok6diUwr9bc'

staging:
  fcm_key: 'AAAARoAcxik:APA91bH3YhwdcexjqMHKtfGIuwhC1huDz_mOYMbPpTLKwQsA28pxyVxS0N-S-WvmJbXBJL9HjBtTqF6YnXqgLxgy-9bBqjoV9DISd-g86LMDd27LIfHbyrEVo0ziO3M3Jok6diUwr9bc'

development:
  fcm_key: 'AAAARoAcxik:APA91bH3YhwdcexjqMHKtfGIuwhC1huDz_mOYMbPpTLKwQsA28pxyVxS0N-S-WvmJbXBJL9HjBtTqF6YnXqgLxgy-9bBqjoV9DISd-g86LMDd27LIfHbyrEVo0ziO3M3Jok6diUwr9bc'
  gmail_username: 'sahilpruthi412@gmail.com'
  gmail_password: '9996190916'